let data={
    "What are Somatic Cells?":"Somatic cells are diploid cells and contain two sets of homologous  chromosomes.A somatic cell is any cell in the body other than cells involved in  reproduction (gametes).",
     "What are Diploid Cells?":"A Diploid cell contains two complete sets of chromosomes, one from each parent. Most cells in the human body are diploid.",
     "How many chromosomes do Diploid cells have?":"Diploid cells in humans have 23 pairs of homologous chromosomes.",
    "What happens to Diploid cells during cell division?":"During cell division the nucleus of a somatic cell divides by mitosis to  maintain the diploid chromosome number.", 
    "How do Somatic cells divide?":"Somatic cells divide by mitosis to form more somatic cells which  differentiate to form different body tissue types",
    "Are Mutations in somantic cells passed to offspring?":"They do not",
    "What are Germline cells?":"Germline cells are gametes (sperm and ova) and the stem cells that divide  to form gametes.", 
    "What 2 ways do the nucleus of Germline cells divide?":"The nucleus of germline cells divide by mitosis to produce more germline  cells (maintaining the chromosome number) or by meiosis to produce  haploid gametes.",
    "Descripe what happens in meiosis of a nucleus of a  Germline cell?":"In meiosis the nucleus of a germline cell undergoes two divisions, firstly  separating homologous chromosomes and secondly separating chromatids. • Haploid gametes contain 23 single chromosomes.",
    "Can mutations in Germline cells be passed on?":"Yes they can",
    "What is cellular differentation?":"Cellular differentiation is the process by which a cell develops more  specialised functions.",
    "How does cellular differentation occur?":"Cellular differentiation occurs by expressing only the genes characteristic of  that type of cell.Once a cell becomes differentiated, it only expresses the genes that  produce the proteins characteristic for that type of cell.",
    "Describe Stem cells?":"Stem cells are relatively unspecialised cells. Stem cells are able to continue to divide to produce more stem cells or cells  which will differentiate into specialised cells of one or more types.",
    "During embryological development what happens to unspecialised cells?":"During embryological development, the unspecialised cells of the early  embryo differentiate into cells with specialised functions. ",
    "Where are Embryonic stem cells found?":"Embryonic stem cells are found in the inner cell mass (epiblast) of the  blastocyst.",
    "What cell types can embryonic stem cells develop into?":"Embryonic stem cells are capable of developing into any of the body's cell  types (pluripotent)",
    "What is the function of adult stem cells?":"Tissue (adult) stem cells replenish differentiated cells that need to be  replaced.",
    "In what numbers are adult stem cells found?":"Tissue (adult) stem cells are found in very small numbers throughout the  body tissues.",
    "What do adult stem cells give rise to?":"Tissue (adult) stem cells give rise to a limited range of cell types typical of  the organ of which they are a part (multipotent). They have a limited  differentiation potential.or example, blood stem cells located in bone marrow can give rise to red  blood cells, platelets, phagocytes and lymphocytes.",
     "Give an example of stem cells giving roise to a limited range of cells?":"For example, blood stem cells located in bone marrow can give rise to red blood cells, platelets, phagocytes and lymphocytes.",
    "Why are stem cells useful for research?":"Stem cells are useful for research because they are capable of giving rise to a range of cell types and can be cultured indefinitely in the laboratory.",
    "What cell  processes have stem cell research contributed to?":"Stem cell research has contributed to our understanding of cell processes such as growth, differentiation and gene regulation.",
    "Stem cells cultured from patients with particular diseases can be used for what?":"Stem cells cultured from patients suffering from particular conditions can be used to produce very specific cultures for use in testing a wide range of drugs, e.g. Alzheimer's disease.",
     "Why do stem cells have theraputic use?":"Stem cells have therapeutic uses because they are pluripotent and can be stimulated in culture to form a wide variety of tissues.",
    "What can stem cells be used for?":"Stem cells can be used in the repair of damaged or diseased organs and  tissues.",
    "In corneal repair what does the use of stem cells do?":"In corneal repair, the use of corneal stem cells from the patient's own tissue speeds up the process, creates new healthy tissue, and reduces the chance of rejection.",
    "How do stem cells assist in cell grafting?":"In skin grafting, the use of epidermal stem cells allows the much more rapid production of a temporary graft, which reduces the risk of dehydration or infection.",
    "What are the principal ethical concerns abput stem cells?":"The principal ethical issues associated with stem cell use in research apply to embryonic stem cell use.The ethical objections to the use of embryonic stem cells are principally that an embryo is destroyed in the process.",
    "Why do cancer cells divide excessively and what does this cause?":"Cancer cells divide excessively because they do not respond to regulatory signals.This results in a mass of abnormal cells called a tumour.",
    "Why do tumours spread throughout the body?":"Cells within the tumour may fail to attach to each other, spreading through the body where they may form secondary tumours.",
    "What is a benign tumour?":"A benign tumour is one which does not invade neighbouring tissues or spread throughout the body.",
    "What is a malignant tumour?":"A malignant tumour is one in which the cells lose the molecules on their surface that normally hold them in place; they can therefore become detached from their neighbours and spread through the body in the blood or lymphatic circulation.",
    "What is the original tumour and the detached cells called?":"The original tumour is called the primary tumour and those forming from the detached cells are called secondary tumours.",
    "What is DNA ?":"DNA is the molecule of inheritance and can direct its own replication.",
    "How do cells store their genetic information?":"All cells store their genetic information in the base sequence of DNA.",
    "How is the genotype determined?":"The genotype is determined by the sequence of DNA bases.",
    "What are chromosomes made of?":"Chromosomes consist of tightly coiled DNA, packaged with associated histone proteins.",
    "What is the basic unit of DNA?":"The basic unit of DNA is the nucleotide",
    "What makes up a DNA nucleotide?":"A DNA nucleotide is composed of deoxyribose sugar, phosphate and an organic nitrogenous base.",
    "How are the carbon atoms of the dexoribose numbered?":"The 5 carbon atoms of the deoxyribose molecule are numbered",
    "How are nucleotides joined?":"Nucleotides are joined by strong covalent bonds to form a sugar-phosphate backbone.",
    "What are the four bases?":"There are four bases: adenine (A), thymine (T), guanine (G) and cytosine(C).",
    "How are the bases joined?":"These bases join to the equivalent base on the opposite strand by weak hydrogen bonds.",
    "What bases join together?":"The complementary pairs are A-T and G-C.",
    "The base pairs hold the 2 strands of the DNA molecule in what shape?":"A double Helix",
    "Describe the structure of DNA?":"DNA is a double-stranded, antiparallel structure with the strands running in opposite directions.",
    "How do you know the direction of the strand?":"The direction of the strand is identified by the carbon atoms of the deoxyribose which are found at the end of the strand.One strand goes from 3’ to 5’ the other from 5’ to 3’.",
    "What is found at the end of the 3'strand and the 5' strand?":"Deoxyribose is found at the 3’ end of the DNA strand and phosphate is found at the 5’ end of the DNA strand.",
    "In DNA replication how is DNA unwound?":"DNA is unwound and unzipped by an enzyme.This forms two template strands.",
    "What enzyme addds nucleotides to the new DNA strand?":"DNA polymerase is the enzyme which adds nucleotides to the new DNA strand.",
    "What does DNA Polymerase need to start replication?":"DNA polymerase needs a primer to start replication.",
    "What end of the of the DNA strand can DNA polymerase add to?":"DNA polymerase can only add complementary nucleotides to the deoxyribose / 3’ end of the DNA strand.This results in the 3’ strand / the leading strand being continuously replicated",
    "How is the 5' strand replicated?":"The 5’ strand / the lagging strand is replicated in fragments.These fragments are joined together (by the enzyme ligase).",
    "What is the name for the process that increase(amplifies) a sample of DNA?":"POLYMERASE CHAIN REACTION",
    "What can PCR be used for?":"PCR can amplify DNA to help solve crimes, settle paternity suits and diagnose genetic disorders.",
    "What is step 1 of PCR?":"Mixing together the components of PCR",
    "Step 2 of PCR?":"Heating (90 - 95◦C) separates the DNA strands.",
    "Step 3 of PCR?":"Annealing (54◦C) is the binding of the primers, which mark the start and end of the sequence to be amplified, as well as preventing reattachment of the separated DNA strands.",
    "Step 4 of PCR?":"Extension (72◦C) (of the primers to complete the complementary strand) is carried out by heat stable DNA polymerase.",
    "How can you amplify the DNA sample?":"Repeated cycles of heating and cooling amplify this region of DNA.",
    "What does PCR have in common with natural cells?":"PCR uses the enzyme DNA polymerase to replicate, or 'amplify', the DNA strand.",
    "How are genes expressed using their DNA code?" : "Genes are expressed by using their DNA code to produce a protein.",
"How is the phenotype determined by the proteins produced by gene expression?" : "The phenotype is determined by the proteins produced by gene expression",
"In any one cell, what fraction of the genome is typically expressed?" : "In any one cell, only a fraction of the genome is expressed.",
"What are the two major stages of gene expression?" : "Gene expression has two major stages: transcription and translation.",
"Where does transcription take place and what does it involve?" : "Transcription takes place in the nucleus and is the transfer of the genetic code from the DNA of the gene to mRNA.",
"Where does translation occur and what is its purpose?" : "Translation takes place at the ribosome in the cytoplasm and is the formation of a polypeptide from the code carried on the mRNA.",
"At which steps can gene expression be controlled during transcription and translation?" : "Gene expression may be controlled at any of the many steps of both transcription and translation.",
"How is the code of the gene represented in DNA?" : "The code of the gene is a series of triplets of bases in DNA.",
"How many possible combinations of three bases exist and what does this imply?" : "There are 64 possible combination of three bases, so 64 different triplets.",
"What is the structure of Ribonucleic acid (RNA)?" : "Ribonucleic acid (RNA) is a single strand of nucleic acid.",
"What does RNA comprise of?" : "RNA comprises ribose sugar, a phosphate group and one of four bases.",
"Which bases does RNA contain?" : "RNA contains 3 of the bases in DNA, namely adenine, guanine and cytosine, plus uracil which replaces the thymine of DNA.",
"How do RNA bases pair?" : "RNA bases pair A-U and G-C, both with DNA and other RNA molecules.",
"What are the three forms of RNA?" : "There are three forms of RNA; (mRNA, tRNA and rRNA)",
"What is the role of Messenger RNA (mRNA)?" : "Messenger RNA (mRNA) carries the code of the gene from the DNA of the nucleus out to a ribosome in the cytoplasm.",
"What is a codon on the mRNA molecule?" : "Each triplet of bases on the mRNA molecule is called a codon and codes for a specific amino acid.",
"How does Transfer RNA (tRNA) fold?" : "Transfer RNA (tRNA) folds due to complementary base pairing.",
"What are the features of a tRNA molecule?" : "A tRNA molecule has an anticodon (an exposed triplet of bases) at one end and an attachment site for a specific amino acid at the other end.",
"What is the role of Transfer RNA (tRNA)?" : "Transfer (tRNA) carries specific amino acids to the mRNA attached to a ribosome.",
"What is the role of Ribosomal RNA (rRNA)?" : "Ribosomal RNA (rRNA) reads the mRNA code in the ribosome.",
"What is transcription in the context of gene information transfer?" : "Transcription is the transfer of the gene information from the triplet code on the DNA template to mRNA.",
"How does RNA polymerase function during transcription?" : "RNA polymerase moves along DNA unwinding the double helix and breaking the hydrogen bonds between the bases. RNA polymerase synthesises a primary transcript of mRNA from RNA nucleotides by complementary base pairing.",
"What is the primary transcript?" : "This strand of mRNA is the primary transcript.",
"What does the primary transcript contain?" : "The primary transcript contains both protein-coding regions (exons) and non-coding regions (introns).",
"What happens after transcription?" : "After transcription, the introns are removed from the primary transcript and the exons are joined together.",
"What is RNA splicing?" : "The joining of the exons is called RNA splicing.",
"What is the final form of mRNA?" : "The final form of the mRNA is the mature transcript.",
"What is translation in the context of gene information conversion?" : "Translation is the conversion of the gene information, in the form of mRNA, into a polypeptide at a ribosome.",
"What do ribosomes comprise of?" : "Ribosomes comprise rRNA and proteins.",
"Which bases does RNA contain?" : "RNA contains 3 of the bases in DNA, namely adenine, guanine and cytosine, plus uracil which replaces the thymine of DNA.",
"How do RNA bases pair?" : "RNA bases pair A-U and G-C, both with DNA and other RNA molecules.",
"What are the three forms of RNA?" : "There are three forms of RNA; (mRNA, tRNA and rRNA)",
"What is the role of Messenger RNA (mRNA)?" : "Messenger RNA (mRNA) carries the code of the gene from the DNA of the nucleus out to a ribosome in the cytoplasm.",
"What is a codon on the mRNA molecule?" : "Each triplet of bases on the mRNA molecule is called a codon and codes for a specific amino acid.",
"How does Transfer RNA (tRNA) fold?" : "Transfer RNA (tRNA) folds due to complementary base pairing.",
"What are the features of a tRNA molecule?" : "A tRNA molecule has an anticodon (an exposed triplet of bases) at one end and an attachment site for a specific amino acid at the other end.",
"What is the role of Transfer RNA (tRNA)?" : "Transfer (tRNA) carries specific amino acids to the mRNA attached to a ribosome.",
"What is the role of Ribosomal RNA (rRNA)?" : "Ribosomal RNA (rRNA) reads the mRNA code in the ribosome.",
"What is transcription in the context of gene information transfer?" : "Transcription is the transfer of the gene information from the triplet code on the DNA template to mRNA.",
"How does RNA polymerase function during transcription?" : "RNA polymerase moves along DNA unwinding the double helix and breaking the hydrogen bonds between the bases. RNA polymerase synthesises a primary transcript of mRNA from RNA nucleotides by complementary base pairing.",
"What is the primary transcript?" : "This strand of mRNA is the primary transcript.",
"What does the primary transcript contain?" : "The primary transcript contains both protein-coding regions (exons) and non-coding regions (introns).",
"What happens after transcription?" : "After transcription, the introns are removed from the primary transcript and the exons are joined together.",
"What is RNA splicing?" : "The joining of the exons is called RNA splicing.",
"What is the final form of mRNA?" : "The final form of the mRNA is the mature transcript.",
"What is translation in the context of gene information conversion?" : "Translation is the conversion of the gene information, in the form of mRNA, into a polypeptide at a ribosome.",
"What do ribosomes comprise of?" : "Ribosomes comprise rRNA and proteins.",
"How does mRNA carry the genetic code?" : "mRNA carries the genetic code in the form of sets of 3 bases called codons.",
"What is an anticodon in tRNA?" : "Each tRNA has three exposed bases called an anticodon.",
"How is each amino acid carried?" : "Each amino acid is carried by a different type of tRNA.",
"What are start and stop codons?" : "One codon acts as start codon and others act as stop codon, indicating the start and finish of translation.",
"What happens when the start codon is reached?" : "When the start codon is reached, the ribosome starts attaching tRNA bases to the mRNA strand.",
"How are anticodons of tRNA molecules matched?" : "The anticodons of the tRNA molecules are matched to complementary codons on the mRNA.",
"How are amino acids joined?" : "Enzymes in ribosome join the amino acids by peptide bonds.",
"What happens to each tRNA after the polypeptide is formed?" : "Each tRNA then leaves the ribosome as the polypeptide is formed.",
"How can different proteins be expressed from one gene?" : "Different proteins can be expressed from one gene, as a result of alternative RNA splicing.",
"How are different mature mRNA transcripts produced?" : "Different mature mRNA transcripts are produced from the same primary transcript depending on the combination of exons retained.",
"How are amino acids linked to form polypeptides?" : "Amino acids are linked by peptide bonds to form polypeptides.",
"How do polypeptide chains fold to form a protein?" : "Polypeptide chains fold to form the three-dimensional shape of a protein, held together by hydrogen bonds and other interactions between individual amino acids.",
"How do proteins determine their functions?" : "Proteins have a large variety of shapes which determines their functions.",
"How is phenotype determined?" : "Phenotype is determined by proteins produced as the result of gene expression.",
"How do environmental factors influence phenotype?" : "Environmental factors also influence phenotype.",
"What are mutations in the context of DNA changes?" : "Mutations are changes in the DNA that can result in no protein or an altered protein being synthesised.",
"What is a gene mutation?" : "A gene mutation is a random change in the number or sequence of bases.",
"What happens when a gene mutation occurs?" : "A gene mutation results in no protein, or a faulty protein, being produced.",
"What are point mutations?" : "Mutations that involve a single nucleotide are called point mutations.",
"What are the types of single gene mutations?" : "Single gene mutations involve substitution, insertion or deletion of nucleotides.",
"What is a substitution mutation?" : "A substitution mutation occurs when one base is replaced by another.",
"What are the types of single-nucleotide substitutions?" : "Single-nucleotide substitutions include: missense, when one amino acid replaces another, e.g. sickle cell disease; nonsense, when an amino acid codon is replaced with a premature stop codon which results in a shorter protein, e.g. Duchenne muscular dystrophy (DMD); splice-site mutations, resulting in the creation or destruction of the codons for exon-intron splicing and result in some introns being retained and/or some exons not being included in the mature transcript. e.g. Beta (β) thalassemia.",
"What is the effect of substitution mutations on the amino acid sequence?" : "Substitution mutations do not usually have a large effect on the amino acid sequence coded unless they involve stop or start codons, introns or exons.",
"What is a deletion mutation?" : "A deletion mutation involves the removal of a base.",
"What is an insertion mutation?" : "An insertion mutation involves the addition of a base.",
"What are insertion and deletion mutations known as and why?" : "Insertion and deletion mutations are known as frameshift mutations because they alter the entire sequence of amino acids coded after them.",
"What is the effect of a frameshift mutation?" : "The effect of a frameshift mutation is greater the earlier in the gene that it occurs as more codons, introns, exons and stop codons will be affected.",
"What is the likely result of frameshift mutations?" : "Frameshift mutations are likely to result in no protein being produced, and so may often be fatal.",
"What is an example of a condition caused by a frameshift insertion mutation?" : "An example of a condition caused by a frameshift insertion mutation is TaySachs syndrome.",
"What is an example of a condition caused by a frameshift deletion mutation?" : "An example of a condition caused by a frameshift deletion mutation is Cystic Fibrosis.",
"What can nucleotide insertions or deletions result in?" : "Nucleotide insertions or deletions can also result in an expansion of a nucleotide sequence repeat - a condition associated with nucleotide repeat expansion is Huntingdon's disease.",
"What are chromosome structural mutations?" : "Chromosome structural mutations are due to the addition, removal or reversal of segments of chromosome.",
"What is the effect of mutations that alter gene expression?" : "Any mutation which alters gene expression is likely to have a serious effect, e.g. by altering start and stop codons, exons, introns and promoters.",
"What forms can chromosome mutations take?" : "Chromosome mutations can take the form of: a deletion, involving the loss of a segment of a chromosome; duplication- a segment of chromosome is added from its homologous partner so is repeated; translocation - is where a section of a chromosome is added to a chromosome, not its homologous partner; inversion, the reversal of a segment of a chromosome.",
"What is the impact of substantial changes in chromosome mutations?" : "The substantial changes in chromosome mutations often make them lethal.",
"What is Cri-du-chat syndrome?" : "Cri-du-chat syndrome is an example of deletion: a part of the short arm of chromosome 5 is missing.",
"What is one cause of Haemophilia A?" : "Haemophilia A — one cause is an inversion within the gene that produces a clotting factor (factor VIII).",
"What is Chronic myeloid leukaemia (CML)?" : "Chronic myeloid leukaemia (CML) is an example of reciprocal translocation: a gene from chromosome 22 is fused with a gene on chromosome 9.",
"What is the genome of an organism?" : "The genome of an organism is its entire hereditary information encoded in DNA.",
"What is a genome made up of?" : "A genome is made up of genes and other DNA sequences that do not code for proteins.",
"What can be determined in genomic sequencing?" : "In genomic sequencing the sequence of nucleotide bases can be determined for individual genes and entire genomes.",
"How can computer programs be used in genomic sequencing?" : "Computer programs can be used to identify base sequences by looking for sequences similar to known genes.",
"What is required to compare sequence data?" : "To compare sequence data, computer and statistical analyses (bioinformatics) are required.",
"How can an individual’s genome be analysed?" : "An individual’s genome can be analysed to predict the likelihood of developing certain diseases.",
"What is Pharmacogenetics?" : "Pharmacogenetics is the use of genome information in the choice of drugs.",
"How can an individual’s personal genome sequence be used?" : "An individual’s personal genome sequence can be used to select the most effective drugs and dosage to treat their disease (personalised medicine).",



}
    export default data;